name: examgo
description: "ExamGO — Secure Exam Browser for Android & iOS"
publish_to: 'none'
version: 2.0.0+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # QR Scanner & Generator
  mobile_scanner: ^7.1.3
  qr_flutter: ^4.1.0

  # WebView
  webview_flutter: ^4.13.0

  # Permissions
  permission_handler: ^12.0.1

  # Gallery (pick QR image)
  image_picker: ^1.2.1

  # Device info (Android SDK version check)
  device_info_plus: ^12.3.0

  # Connectivity
  connectivity_plus: ^7.0.0

  # Local storage
  shared_preferences: ^2.2.2

  # Cryptography — QR signing (HMAC-SHA256)
  crypto: ^3.0.5

  # HTTP
  http: ^1.1.0
  
  # Save QR image to temp + share
  path_provider: ^2.1.4
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true